### ISSUE TITLE
egg-bull 不支持process ts文件

### ISSUE THREAD

**Issue by webignorant** [brickyang/egg-bull#8]
3.5.3版本bull限制只能使用js文件，3.6.0已经移除该限制。
考虑升级当前bull的包依赖

**Comment by brickyang** [comment]
`package.json` 中是 `bull: ^3.5.2`，只要主版本不超过 `3` 都会自动安装最新版。

**Comment by webignorant** [comment]
@brickyang 参考egg-queue-bull，建议考虑对外部queue文件提供egg注入支持。

**Comment by brickyang** [comment]
这是另一个话题吧？如果关于这个 issue 的主题没有更多疑问就先关闭了（如果我理解错了，也欢迎说明并重开）。

关于注入 queue 文件，我对其必要性还没仔细考虑过。可以的话你可以新开一个 issue 具体说明下自己的想法。
